version: '3.8'
services:
  vprodb:
    build: ./Docker-files/db
    image: prosen25/vprofiledb
    container_name: vprodb
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
  
  vprocache:
    image: memcached
    ports:
      - "11211:11211"

  vprormq:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build: ./Docker-files/app
    image: prosen25/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: ./Docker-files/web
    image: prosen25/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}