pipeline {
    agent any

    environment {
        REGISTRY_CREDENTIAL = 'awscreds'
        AWS_REGION = 'us-east-1'
        ECS_CLUSTER_NAME = 'vprofile-prod'
        ECS_SERVICE_NAME = 'vpro-app-prod-svc'
    }

    stages {
        stage('Deploy to Prod ECS') {
            steps {
                withAWS(credentials: "${REGISTRY_CREDENTIAL}", region: "${AWS_REGION}") {
                    sh 'aws ecs update-service --cluster ${ECS_CLUSTER_NAME} --service ${ECS_SERVICE_NAME} --force-new-deployment'
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image deployed successfully to Prod ECS'
        }

        failure {
            echo 'Failed to deploy Docker image to Prod ECS'
        }
    }

}